application:
  name: zall

workflow:
  callback:
    url: http://127.0.0.1:80/api/v1/workflow/internal/taskCallBack
    token: 123

http:
  port: 80

app:
  url: http://127.0.0.1
  lang: en-US

xorm:
  dataSourceName: root:root@tcp(127.0.0.1:3306)/hhhh?charset=utf8

git:
  proxy:
    server:
      enabled: true
      port: 5555
  repo:
    server:
      port: 4444
      enabled: true

httptask:
  token: 123

prom:
  agent:
    enabled: true
    env: sit
    filePath: /Users/lizexin/Desktop/prometheus/prometheus-2.51.1.darwin-amd64/target.json
    endpoint: prom-001

zallet:
  enabled: true
  cmd: /Users/lizexin/go/src/zallet/zallet
  sock: /Users/lizexin/go/src/zallet/data/zallet.sock

wework:
  accessToken:
    task:
      enabled: true

feishu:
  accessToken:
    task:
      enabled: true