application:
  name: zgit

ssh:
  proxy:
    port: 2222

actions:
  enabled: true

app:
  url: http://127.0.0.1
  lang: en-US
  corpId: zexin5

xorm:
  dataSourceName: root:root@tcp(127.0.0.1:3306)/hhhh?charset=utf8

git:
  proxy:
    server:
      port: 5555
  repo:
    server:
      enabled: true

timer:
  enabled: true
  env: dev

idserver:
  enabled: true

propserver:
  enabled: true

httptask:
  token: 123

tcpDetect:
  enabled: true

discovery:
  type: static

files:
  enabled: true
  normal:
    token: 123
  domain: http://localhost

action:
  agent:
    enabled: true

probe:
  enabled: true
  env: sit
