application:
  name: zgit

ssh:
  proxy:
    port: 2222

workflow:
  callback:
    token: 123
  agent:
    enabled: true
    port: 6666
    token: nihao

app:
  url: http://127.0.0.1
  lang: en-US
  corpId: zexin5

xorm:
  dataSourceName: root:root@tcp(127.0.0.1:3306)/hhhh?charset=utf8

git:
  proxy:
    server:
      port: 5555
  repo:
    server:
      enabled: true

timer:
  enabled: true
  env: dev

idserver:
  enabled: true

propserver:
  enabled: true

httptask:
  token: 123

tcpDetect:
  enabled: true

discovery:
  type: static

files:
  enabled: true
  normal:
    token: 123
  domain: http://localhost

action:
  agent:
    enabled: true

probe:
  enabled: true
  env: sit

prom:
  agent:
    enabled: true
    env: sit
    filePath: /Users/lizexin/Desktop/prometheus/prometheus-2.51.1.darwin-amd64/target.json
    serverUrl: http://127.0.0.1:9090

logger:
  loki:
    enabled: true
    orgId: local
    pushUrl: http://127.0.0.1:3100/loki/api/v1/push

alert:
  enabled: true