package git

import (
	"fmt"
	"github.com/LeeZXin/zall/util"
	"os"
	"path/filepath"
)

const (
	ScriptType = "bash"
)

func preReceiveHook() string {
	return fmt.Sprintf(`#!/usr/bin/env %s
# AUTO GENERATED BY github.com/LeeZXin/zall, DO NOT MODIFY
data=$(cat)
echo "${data}" | %s gitHook pre-receive
exit $?
`, ScriptType, util.ShellEscape(util.GetAppPath()))
}

func postReceiveHook() string {
	return fmt.Sprintf(`#!/usr/bin/env %s
# AUTO GENERATED BY github.com/LeeZXin/zall, DO NOT MODIFY
data=$(cat)
echo "${data}" | %s gitHook post-receive
exit $?
`, ScriptType, util.ShellEscape(util.GetAppPath()))
}

func InitRepoHook(repoPath string) error {
	hookDir := filepath.Join(repoPath, "hooks")
	hook := preReceiveHook()
	if err := writeHookFile(filepath.Join(hookDir, "pre-receive"), []byte(hook)); err != nil {
		return fmt.Errorf("init pre-receive hook file failed: %v", err)
	}
	hook = postReceiveHook()
	if err := writeHookFile(filepath.Join(hookDir, "post-receive"), []byte(hook)); err != nil {
		return fmt.Errorf("init post-receive hook file failed: %v", err)
	}
	return nil
}

func writeHookFile(filePath string, content []byte) error {
	if err := util.RemoveAll(filePath); err != nil && !os.IsNotExist(err) {
		return err
	}
	if err := os.WriteFile(filePath, content, 0o777); err != nil {
		return err
	}
	return ensureExecutable(filePath)
}

func ensureExecutable(filePath string) error {
	fileInfo, err := os.Stat(filePath)
	if err != nil {
		return err
	}
	if (fileInfo.Mode() & 0o100) > 0 {
		return nil
	}
	mode := fileInfo.Mode() | 0o100
	return os.Chmod(filePath, mode)
}
